# Generated by Django 4.1.6 on 2023-02-11 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0002_rename_ingredients_topping"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="topping",
            field=models.ManyToManyField(
                related_name="pizza_topping", to="delivery.topping"
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("status", models.CharField(max_length=63)),
                (
                    "pizza",
                    models.ManyToManyField(related_name="order", to="delivery.pizza"),
                ),
                (
                    "topping",
                    models.ManyToManyField(
                        related_name="cart_topping", to="delivery.topping"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="delivery.order"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="payment",
            name="customer_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="delivery.order"
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
