# Generated by Django 4.1.6 on 2023-02-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0003_pizza_topping_order_bucket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="customer_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="delivery.bucket"
            ),
        ),
    ]
