# Generated by Django 4.1.6 on 2023-02-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0009_remove_order_quantity_pizza_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pizza",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
