# Generated by Django 4.1.6 on 2023-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0010_remove_pizza_quantity_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="pizza_change_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
