# Generated by Django 4.1.6 on 2023-02-17 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0011_pizza_pizza_change_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment",
            new_name="Receipt",
        ),
    ]
