# Generated by Django 4.1.6 on 2023-02-18 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0013_remove_order_quantity_pizza_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pizza",
            name="pizza_change_price",
        ),
    ]
