# Generated by Django 4.1.6 on 2023-02-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0014_remove_pizza_pizza_change_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="price_with_toppings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
