# Generated by Django 4.1.6 on 2023-02-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0015_pizza_price_with_toppings"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="is_custom_pizza",
            field=models.BooleanField(default=False),
        ),
    ]
