# Generated by Django 4.1.6 on 2023-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0016_pizza_is_custom_pizza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="topping",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="pizza_topping",
                to="delivery.topping",
            ),
        ),
    ]
